spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.150.146:8848
        namespace: nacos-client
server:
  servlet:
    context-path: /nacos-client-user
  port: 8081
remote:
  order:
    url:
      pre: http://nacos-client-order
      get-service-name: /nacos-client-order/test

